### ISSUE TITLE
Variables de sesión

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/integrador-ago-dic-2019#142]
Además del correo ¿podrías agregar en la sesión el id del usuario, nombre y apellidos? 

https://github.com/UniversidadCristobalColon/integrador-ago-dic-2019/blob/6d4e7896b9c6199b6f39f713e00a2e246a515dcc/app/login.php#L153

**Comment by foo1024bar** [comment]
Commit 34f2e55a452fce49425727565d74e04831eb592c
