### ISSUE TITLE
Mensaje correo cambio contraseña

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/integrador-ago-dic-2019#146]
El texto para el correo de cambio de contraseña:

> ¡Hola!
> 
> Se ha solicitado un cambio de contraseña de acceso a su cuenta. Da clic en la siguiente liga de Internet para realizar el cambio:
> 
> {{sustituir con la liga de cambio de contraseña}}
> 
> Si no lo has solicitado tú, te recomendamos ingresar a la aplicación y cambiar tu contraseña para proteger tu cuenta.
> 
> Saludos.

**Comment by foo1024bar** [comment]
Commit 34f2e55a452fce49425727565d74e04831eb592c
